version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/status_notification/data # Монтируем папку data
    environment:
      - DATABASE=/status_notification/data/monitoring.db # Указываем путь к БД в монтируемой папке
    restart: always
