version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data # Монтируем папку data
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL=30
      - ALLOWED_DELAY=300
    ports:
      - "5000:5000"
    restart: always
