version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/status_notification/data # Монтируем папку data
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL=600
      - ALLOWED_DELAY=1200
    ports:
      - "8050:8050"
    restart: always
